FROM apache/airflow:slim-2.5.0rc2-python3.10

USER airflow

RUN pip install psycopg2-binary \
    pip install sqlalchemy==1.4.36 \
    pip install pandas==2.1.4 \
    pip install selenium \
    pip install numpy \
    pip install bs4 \
    pip install requests \
    pip install minio
